set.seed(123)

## Set up coordinate system
coordinates <- as.matrix(expand.grid(1:10, 1:10))

## Generate data set with three distinct genes generated by three
## distinct cell types
profiles <- diag(rep(1, 3)) + runif(9)
centers <- cbind(c(5, 2), c(2, 8), c(8, 2))
mixes <- apply(coordinates, 1, function(x) {
    x <- exp(-colSums((centers - x) ^ 2) / 50)
    x / sum(x)
})
means <- 100 * profiles %*% mixes
counts <- matrix(rpois(prod(dim(means)), means), nrow = nrow(profiles))
colnames(counts) <- apply(
    coordinates,
    1,
    function(x) do.call(paste, c(as.list(x), list(sep = "x")))
)
rownames(counts) <- paste("gene", 1:nrow(counts))

## Create App
SpatialCPie:::.makeApp(
    counts = counts,
    image = NULL,
    coordinates = NULL,
    margin = "spot",
    resolutions = 2:4,
    assignmentFunction = function(x, k) kmeans(x, centers =  k)$cluster
)
